### ISSUE TITLE
Make it run on with bash 4.3.46(1)-release (x86_64-pc-linux-gnu)

### ISSUE THREAD

**Issue by sirfoga** [remy/check#1]
You have to ```bash check <url>``` instead of ```./check <url>```

**Comment by remy** [comment]
Do you mean it didn't have the right permissions (i.e. `chmod u+x`) or that it didn't work at all?

**Comment by sirfoga** [comment]
```chmod u+x check && ./check``` would result in ```./check: 5: ./check: function: not found```

**Comment by remy** [comment]
Yeah, I spotted that on my rudimentary run on a linux machine (hence the not in the readme). Do you know how to fix? Hugely appreciate a PR for it 🙏

**Comment by sirfoga** [comment]
Yeah .. sort of .. it seems that the statement ```function blabla() {}``` it's not POSIX-compliant; I'm trying to fix this.

**Comment by remy** [comment]
👍 (thanks so much)

**Comment by sirfoga** [comment]
Opened a pull request, works fine in my system, however I havent' a OSX handy, try it for confirmation.
